version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  target-branch: "main"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  commit-message:
    prefix: "Deps"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "Deps"
