# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup, find_packages
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='pheme',
    version='0.0.1.dev3',
    description='report-generation-service',
    python_requires='==3.*,>=3.7.0',
    author='Greenbone Networks GmbH',
    author_email='info@greenbone.net',
    license='AGPL-3.0-or-later',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Operating System :: OS Independent',
        'Topic :: Internet :: WWW/HTTP :: WSGI :: Server',
    ],
    entry_points={
        "console_scripts": [
            "pheme-create-parameter-json = pheme.scripts.parameter:main"
        ]
    },
    packages=find_packages(exclude=['tests']),
    include_package_data=True,
    install_requires=[
        'coreapi==2.*,>=2.3.3',
        'django==3.*,>=3.1.0',
        'djangorestframework==3.*,>=3.11.1',
        'djangorestframework-dataclasses<0.9,>=0.6',
        'matplotlib==3.0.2',
        'pyyaml==5.*,>=5.3.1',
        'rope<0.19,>=0.17',
        'uritemplate==3.*,>=3.0.1',
        'weasyprint<53,>=51',
        'xmltodict==0.*,>=0.12.0',
    ],
    extras_require={
        "dev": [
            "autohooks==2.*,>=2.2.0",
            "autohooks-plugin-black==1.*,>=1.2.0; python_version == \"3.*\" and python_version >= \"3.6.0\"",
            "autohooks-plugin-pylint==1.*,>=1.2.0",
            "black==20.8b1; python_version == \"3.*\" and python_version >= \"3.6.0\"",
            "pontos==0.*,>=0.3.0",
            "pylint==2.*,>=2.6.0",
            "pylint-django==2.*,>=2.3.0",
            "pytest==6.*,>=6.0.1",
            "pytest-cov==2.*,>=2.10.0",
            "pytest-django<5.0,>=3.9",
            "pytest-env==0.*,>=0.6.2",
        ]
    },
    test_suite="tests",
)
