name: Build and test Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v3
      - name: Check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v3
        with:
          formatter: ruff format --diff
          packages: pheme tests

  test:
    name: Run all tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v3
      - name: Run unit tests
        run: poetry run python -m pytest

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v3
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          test-command: -m pytest
          token: ${{ secrets.CODECOV_TOKEN }}
